require("tlast.cmp.setup")

require("tlast.cmp.arduino")
require("tlast.cmp.bash")
require("tlast.cmp.clangd")
require("tlast.cmp.html")
require("tlast.cmp.css")
require("tlast.cmp.java")
require("tlast.cmp.js")
require("tlast.cmp.emmet")
require("tlast.cmp.lua")
require("tlast.cmp.python")
