#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

export MENUCMD="dmenu"
export IMAGE="feh"
# Autostart these programs
{ 
    xcompmgr &
    feh --no-fehbg --bg-scale ~/pics/wallpaper
    setxkbmap colemak -option ctrl:swapcaps,altwin:menu_win
    # xautolock -locker slock &
    gammastep -m randr &
    ntfy transmission &
    # dunst &
    slstatus &
    upds &
    eval "$(keychain --dir "$XDG_CONFIG_HOME/keychain" --eval --quiet --agents gpg,ssh)"
    unclutter --timeout 3 --jitter 50 -b
    herbimisu &
    202020 &
    
    signal-desktop &
    discord &
    st -e "sh" "-c" "pgrep tmux && tmux a || tmux" &
}

exec startdwm
