require("user.packer")
require("user.remap")
require("user.set")
require("user.cmp")
require("user.zk")
require("user.live-server")
vim.cmd.source(vim.fn.stdpath("config") .. "/lua/user/aucommands.vim")
