#!/bin/zsh
# s/alias \([^-]\)/alias -g \1

if grep -qi "debian\|ubuntu" /etc/os-release
then
	alias aptup='apt update && apt upgrade -y'
fi

# Programs
alias nv='nvim'
alias nb='newsboat'
alias sr='surfraw'
alias ccu='calcurse'

alias arduino-cli='arduino-cli --config-file $XDG_CONFIG_HOME/arduino15/arduino-cli.yaml'

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    # alias ls='ls -h --color --group-directories-first'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias ip='ip -color=auto'
fi

alias l='ls -l'
alias l1='ls -1'
alias ll='ls -la'
alias la='ls -aF'
alias lst='ls --tree'
alias lst1='ls --tree -L1'
alias lst2='ls --tree -L2'
alias lst3='ls --tree -L3'
alias ls.='ls -dl .*'
alias ls='exa --sort extension --group-directories-first'

# pacman aliases
alias pac='pacman'
alias pacsi='pac -Si'
alias pacs='pac -Ss'
alias pacq='pac -Ql'
alias pacqe='pac -Q'
alias pacqs='pac -Qs'

alias pacup='dopac -Syu'
alias dopac='doas pacman'
alias orpac='pacman -Qtdq | dopac -Rns - 2> /dev/null || echo "No orphans."'
alias dopacs='dopac -S'
alias dopacc='dopac -Sc'
alias doprm='dopac -Rns'

alias yay='pikaur'
alias yup='yay -Syu'
alias ysi='yay -Si'
alias yss='yay -Ss'
alias yqs='yay -Qs'
alias yql='yay -Ql'
alias yays='yay -S'
alias yrm='yay -Rns'
# 
# 
# -----------------------------------------------------------

alias grub-update='doas grub-mkconfig -o /boot/grub/grub.cfg'

# vim
alias scr='nvim +"setlocal buftype=nofile bufhidden=hide noswapfile filetype=txt" scratch'
alias vimp="vim '+PlugInstall'"
alias nvimp="nvim '+PackerSync'"
alias nvg='git status > /dev/null 2>&1 && nv "+Git"'
alias nvn='nv "+Telekasten panel"'
 
alias -g xclipp='xclip -selection clipboard -r'
alias -g xclipo='xclip -o -selection clipboard -r'
alias -g xclippc='xclip -o -selection primary | xclip -selection clipboard -r'
alias -g xclipcp='xclip -o -selection clipboard | xclip'
 
alias xrandr-rpgmaker='xrandr --auto --output VGA-1 --mode 1024x768 --left-of HDMI-1 && ~/.fehbg'
alias xrandr-default='xrandr --auto --output VGA-1 --mode 1920x1080 --left-of HDMI-1 --output HDMI-1 --mode 1920x1080 && ~/.fehbg'
 
alias dud='du * -d 0 -h 2>/dev/null | sort -h'
alias df='df -h'
alias shred='shred -uz'
alias lsblk='lsblk -o name,type,fsused,size,fstype,label,mountpoint'
alias floc='doas find / -type "f" 2> /dev/null | grep'
alias dloc='doas find / -type "d" 2> /dev/null | grep'
alias fif='find . -type "f" | grep'
alias fid='find . -type "d" | grep'

# ssh
alias sha='ssh-add'
alias ssh-start='eval "$(ssh-agent)" && ssh-add'

alias vidlen='ffprobe -show_entries format=duration -v quiet -of csv="p=0" -i'
alias whatsmyip='curl "ifconfig.me"'
alias icognito='unset HISTFILE'
alias webcam='v4l2-ctl --set-fmt-video=width=1280,height=720; mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0 --profile=low-latency --untimed --no-resume-playback'
alias wtip='wt ip -c -brief addr'
# swallow gui
if which devour > /dev/null
then
	alias mpv='devour mpv'
	alias zathura='devour zathura'
fi

# Python
alias penv='python3 -m venv env'
alias pipreq='pip install -r requirements.txt'

alias -g '...'='../..'
alias -g '....'='../../..'
alias -g bg='&; disown'
alias -g cx='chmod +x'
alias -g ch='chown ${USER}:${USER} -R'
alias -g hl='--help |& less -r'
alias -g pi='ping archlinux.org -c4'
alias -g sba='source env/bin/activate || source bin/activate'
alias -g smc='systemctl'
alias -g smcu='systemctl --user'
alias zsr='source ${ZDOTDIR:-$HOME}/.zshrc && rehash'
alias -g wf='doas wipefs -a'
alias -g dmci="doas make clean install"
alias rmd='rm -f *.{orig,rej}'

# quick config
alias ez='$EDITOR ${ZDOTDIR:-$HOME}/.zshrc'
alias eza='$EDITOR ${ZDOTDIR}/aliases.zsh'
alias ezf='$EDITOR ${ZDOTDIR}/functions.zsh'
alias eto='$EDITOR ~/sync/TODO'
alias edw='$EDITOR ~/src/dwm/config.def.h'
alias edm='$EDITOR ~/src/dmenu/config.def.h'
alias ehst='$EDITOR $ZDOTDIR/histfile'
alias ezh=' $EDITOR $HOME/.config/hypr/hyprland.conf'
alias est='$EDITOR ~/src/st/config.def.h'
alias esl='$EDITOR ~/src/slock/config.def.h'
alias esls='$EDITOR ~/src/slstatus/config.def.h'
alias cfd='$EDITOR config.def.h'
alias cdo='$HOME/src/dotfiles'

# googoo aliases
alias o.='o .'
alias go.='go .'
alias ogo.='ogo .'
alias o/='o /'
alias go/='go /'
alias ogo/='ogo /'

alias fzps='ps aux | tail +2 | fzf --bind \
"1:execute(echo -n {} | awk '\''{print \$1}'\'' | xclip -sel c -r),\
2:execute(echo -n {} | awk '\''{print \$2}'\'' | xclip -sel c -r),\
3:execute(echo -n {} | awk '\''{print \$7}'\'' | xclip -sel c -r),\
4:execute(echo -n {} | awk '\''{print \$9}'\'' | xclip -sel c -r),\
5:execute(echo -n {} | tr -s '\'' '\'' | cut -f 11- -d '\'' '\'' | xclip -sel c -r)"'
alias asf='alias | fzf'

alias -s conf="$EDITOR"
alias -s txt="$EDITOR"
alias -s c="$EDITOR"
alias -s z80="$EDITOR"
alias -s zip='unzip -l'
alias -s tar='tar tf'

alias cfg='git --git-dir=$HOME/src/dotfiles/.git --work-tree=$HOME/src/dotfiles'
# oh-my-zsh git aliases
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gapa='git add --patch'
alias gau='git add --update'
alias gav='git add --verbose'
alias gap='git apply'
alias gapt='git apply --3way'
alias gb='git branch'
alias gba='git branch --all'
alias gbd='git branch --delete'
alias gbda='git branch --no-color --merged | command grep -vE "^([+*]|\s*($(git_main_branch)|$(git_develop_branch))\s*$)" | command xargs git branch --delete 2>/dev/null'
alias gbD='git branch --delete --force'
alias gbg='git branch -vv | grep ": gone\]"'
alias gbgd='local res=$(gbg | awk '"'"'{print $1}'"'"') && [[ $res ]] && echo $res | xargs git branch -d'
alias gbgD='local res=$(gbg | awk '"'"'{print $1}'"'"') && [[ $res ]] && echo $res | xargs git branch -D'
alias gbl='git blame -b -w'
alias gbnm='git branch --no-merged'
alias gbr='git branch --remote'
alias gbs='git bisect'
alias gbsb='git bisect bad'
alias gbsg='git bisect good'
alias gbsr='git bisect reset'
alias gbss='git bisect start'
alias gc='git commit --verbose'
alias gc!='git commit --verbose --amend'
alias gcn!='git commit --verbose --no-edit --amend'
alias gca='git commit --verbose --all'
alias gca!='git commit --verbose --all --amend'
alias gcan!='git commit --verbose --all --no-edit --amend'
alias gcans!='git commit --verbose --all --signoff --no-edit --amend'
alias gcam='git commit --all --message'
alias gcsm='git commit --signoff --message'
alias gcas='git commit --all --signoff'
alias gcasm='git commit --all --signoff --message'
alias gcb='git checkout -b'
alias gcf='git config --list'
alias gcl='git clone'
alias gclr='git clone --recurse-submodules'
alias gc1='git clone --depth 1'
alias gclean='git clean --interactive -d'
alias gpristine='git reset --hard && git clean --force -dfx'
alias grsf='git reset --soft HEAD~'
alias gcm='git checkout $(git_main_branch)'
alias gcd='git checkout $(git_develop_branch)'
alias gcmsg='git commit --message'
alias gco='git checkout'
alias gcor='git checkout --recurse-submodules'
alias gcount='git shortlog --summary --numbered'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gcs='git commit --gpg-sign'
alias gcss='git commit --gpg-sign --signoff'
alias gcssm='git commit --gpg-sign --signoff --message'
alias gd='git diff'
alias gdca='git diff --cached'
alias gdcw='git diff --cached --word-diff'
alias gdct='git describe --tags $(git rev-list --tags --max-count=1)'
alias gds='git diff --staged'
alias gdt='git diff-tree --no-commit-id --name-only -r'
alias gdup='git diff @{upstream}'
alias gdw='git diff --word-diff'
alias gdl='git diff HEAD^ HEAD'
alias gf='git fetch'
alias gfo='git fetch origin'
alias gfg='git ls-files | grep'
alias gg='git gui citool'
alias gga='git gui citool --amend'
alias ggpur='ggu'
alias ggpull='git pull origin "$(git_current_branch)"'
alias ggpush='git push origin "$(git_current_branch)"'
alias ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias ghh='git help'
alias gignore='git update-index --assume-unchanged'
alias gignored='git ls-files -v | grep "^[[:lower:]]"'
alias git-svn-dcommit-push='git svn dcommit && git push github $(git_main_branch):svntrunk'
alias gk='\gitk --all --branches &!'
alias gke='\gitk --all $(git log --walk-reflogs --pretty=%h) &!'
alias gl='git pull'
alias glg='git log --stat'
alias glgp='git log --stat --patch'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glo='git log --oneline --decorate'
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias glols="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --stat"
alias glod="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'"
alias glods="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
alias glola="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --all"
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias glp="_git_log_prettily"
alias gm='git merge'
alias gmom='git merge origin/$(git_main_branch)'
alias gmtl='git mergetool --no-prompt'
alias gmtlvim='git mergetool --no-prompt --tool=vimdiff'
alias gmum='git merge upstream/$(git_main_branch)'
alias gma='git merge --abort'
alias gp='git push'
alias gpd='git push --dry-run'
alias gpf!='git push --force'
alias gpoat='git push origin --all && git push origin --tags'
alias gpod='git push origin --delete'
alias gpr='git pull --rebase'
alias gpu='git push upstream'
alias gpv='git push --verbose'
alias gr='git remote'
alias gra='git remote add'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbd='git rebase $(git_develop_branch)'
alias grbi='git rebase --interactive'
alias grbm='git rebase $(git_main_branch)'
alias grbom='git rebase origin/$(git_main_branch)'
alias grbo='git rebase --onto'
alias grbs='git rebase --skip'
alias grev='git revert'
alias grh='git reset'
alias grhh='git reset --hard'
alias groh='git reset origin/$(git_current_branch) --hard'
alias grm='git rm'
alias grmc='git rm --cached'
alias grmv='git remote rename'
alias grrm='git remote remove'
alias grs='git restore'
alias grset='git remote set-url'
alias grss='git restore --source'
alias grst='git restore --staged'
alias grt='cd "$(git rev-parse --show-toplevel || echo .)"'
alias gru='git reset --'
alias grup='git remote update'
alias grv='git remote --verbose'
alias gsb='git status --short --branch'
alias gsd='git svn dcommit'
alias gsh='git show'
alias gsi='git submodule init'
alias gsps='git show --pretty=short --show-signature'
alias gsr='git svn rebase'
alias gss='git status --short'
alias gst='git status'
alias gstaa='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'
alias gstu='gsta --include-untracked'
alias gstall='git stash --all'
alias gsu='git submodule update'
alias gsw='git switch'
alias gswc='git switch --create'
alias gswm='git switch $(git_main_branch)'
alias gswd='git switch $(git_develop_branch)'
alias gts='git tag --sign'
alias gtv='git tag | sort -V'
alias gtl='gtl(){ git tag --sort=-v:refname -n --list "${1}*" }; noglob gtl'
alias gunignore='git update-index --no-assume-unchanged'
alias gunwip='git log --max-count=1 | grep -q -c "\--wip--" && git reset HEAD~1'
alias gup='git pull --rebase'
alias gupv='git pull --rebase --verbose'
alias gupa='git pull --rebase --autostash'
alias gupav='git pull --rebase --autostash --verbose'
alias gupom='git pull --rebase origin $(git_main_branch)'
alias gupomi='git pull --rebase=interactive origin $(git_main_branch)'
alias glum='git pull upstream $(git_main_branch)'
alias gluc='git pull upstream $(git_current_branch)'
alias gwch='git whatchanged -p --abbrev-commit --pretty=medium'
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"'
alias gwt='git worktree'
alias gwta='git worktree add'
alias gwtls='git worktree list'
alias gwtmv='git worktree move'
alias gwtrm='git worktree remove'
alias gam='git am'
alias gamc='git am --continue'
alias gams='git am --skip'
alias gama='git am --abort'
alias gamscp='git am --show-current-patch'
